### ISSUE TITLE
Get Pool address using contract address

### ISSUE THREAD

**Issue by reachmeharsha8** [Popura-M/BSCScanEnhancer#1]
Off topic :

Is it possible to get Pool address and its balance using contract address ?

**Comment by Popura-M** [comment]
I probably won't be upgrading this script anymore but indeed it is very possible.
Assuming you know the corresponding token (TOKEN-WBNB or TOKEN-BUSD) and its factory (PancakeSwap, BakerySwap, ApeSwap) then you can do it like this using web3 library.

I'll be using part of the code from the script `getTokenInfo(tokenAddress)` function.
`
let tokenAddress = /* Contract address of your token */
const PANCAKE_FACTORY_V2 = '0xcA143Ce32Fe78f1f7019d7d551a6402fC5350c73';
const WBNB_ADDRESS = '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c';
const PANCAKE_FACTORY_V2_ABI = /* ABI of factory here*/
const TOKEN_ABI = /* BEP20 ABI here */
const HTTP_PROVIDER_LINK = /* Your BSC provider link here */

let web3 = new Web3Eth(new Web3Eth.providers.HttpProvider(HTTP_PROVIDER_LINK));
let pancakeFactory = new web3.Contract(PANCAKE_FACTORY_V2_ABI, PANCAKE_FACTORY_V2);

// First we get LP Address of the token with your desiring pair
let poolAddress = await pancakeFactory.methods.getPair(tokenAddress, WBNB_ADDRESS).call();

// Next we create contract instance of token and it pair
let tokenContract = new web3.Contract(TOKEN_ABI, tokenAddress);
let wbnbContract = new web3.Contract(TOKEN_ABI, WBNB_ADDRESS);

// Then we use BEP20's "balanceOf" function to get the balance of the above pool. (divide by 10^18 if token has 18 digits)
let tokenBalanceOfPool = tokenContract.methods.balanceOf(poolAddress).call())/10**18;
let wbnbBalanceOfPool = wbnbContract.methods.balanceOf(poolAddress).call())/10**18;

console.log("Pool's Token Balance: " + tokenBalanceOfPool);
console.log("Pool's WBNB Balance: " + wbnbBalanceOfPool);
`
Something like this should work.
